
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-kubelet-api-admin-bind
subjects:
- kind: ServiceAccount
  name: sa-kubelet-api-admin
  namespace: kubgo
roleRef:
  kind: ClusterRole
  name: system:kubelet-api-admin
  apiGroup: rbac.authorization.k8s.io
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-kubelet-api-admin
  namespace: kubgo
